name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Run clippy (safety checks)
        run: cargo clippy -- -A clippy::not_unsafe_ptr_arg_deref -A clippy::missing_panics_doc -A unused_unsafe -A unsafe_code -D warnings

      - name: Build with cargo-make
        run: cargo make build

      - name: Verify with JPL standards
        run: cargo make verify

      - name: Run tests
        run: cargo test --release

      - name: Strip binary for size optimization
        run: strip target/release/libspotifyadblock.so

      - name: Create build artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-adblock.so
          path: target/release/libspotifyadblock.so

      - name: Verification report
        run: |
          echo "## Build Verification Report" >> $GITHUB_STEP_SUMMARY
          echo "✅ Safety checks passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ JPL standards verified" >> $GITHUB_STEP_SUMMARY
          echo "✅ Binary size: $(du -h target/release/libspotifyadblock.so | cut -f1)" >> $GITHUB_STEP_SUMMARY
